[project]
name = "ragudemy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chromadb>=1.3.5",
    "datasets>=4.4.1",
    "docx2txt>=0.9",
    "faiss-cpu>=1.13.0",
    "huggingface-hub>=0.36.0",
<<<<<<< HEAD
    "ipywidgets>=8.1.8",
=======
>>>>>>> f64f82547c670b662c90e110751adb6f33f172de
    "jq>=1.10.0",
    "langchain>=1.0.8",
    "langchain-classic>=1.0.0",
    "langchain-community>=0.4.1",
    "langchain-groq>=1.0.1",
    "langchain-huggingface>=1.0.1",
    "langchain-openai>=1.0.3",
    "matplotlib>=3.10.7",
    "msoffcrypto-tool>=5.4.2",
    "openpyxl>=3.1.5",
    "packaging>=25.0",
    "pandas>=2.3.3",
    "pymupdf>=1.26.6",
    "pypdf>=6.3.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "sentence-transformers>=5.1.2",
    "tiktoken>=0.12.0",
    "transformers>=4.57.1",
    "unstructured[docs]>=0.18.20",
    "urllib3>=2.5.0",
]
